#Setting up workflow for nuget (continuous deployment)

name: "Release to Nuget (Automatic Versioning) 📄🛠️🚀📦💾🌐"

on:
  push:
    tags:
       - "v*"

env:
  PROJECT_PATH: 'src/SHJ.PersianCulture/SHJ.PersianCulture.csproj'
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'
  

jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'windows-latest'

    steps:
    - name: '📄 Checkout'
      uses: actions/checkout@v2
    
    - name: '🛠️ Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: '🛠️ Restore packages'
      run: dotnet restore  ${{ env.PROJECT_PATH }}
    
    - name: '💾 Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release

    - name: '🚀 Get version'
      id: version
      uses: battila7/get-version-action@v2

    - name: '📦 Deploy NuGet Package'
      run: dotnet pack ${{ env.PROJECT_PATH }} --configuration Release  -p:PackageVersion=${{steps.version.outputs.version-without-v}} 

    - name: '🌐 Push package'
      run: dotnet nuget push ${{env.PROJECT_PATH}}/*.nupkg -k ${{secrets.NUGET_AUTH_KEY}}  -s ${{ env.NUGET_SOURCE_URL }}

      
