#Setting up workflow for nuget (continuous deployment)

name: "Release to Nuget (Automatic Versioning) 📄🛠️🚀📦💾🌐"

on:
  push:
    tags:
       - "v*"

env:
  PROJECT_PATH: 'src/SHJ.PersianCulture/SHJ.PersianCulture.csproj'
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'
  

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-lates

    steps:
    - name: '📄 Checkout'
      uses: actions/checkout@v2
    
    - name: '🛠️ Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    
    - name: '💾 Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release

    - name: '🚀 Get version'
      id: version
      uses: battila7/get-version-action@v2

    - name: '📦 Create NuGet Package'
      run: dotnet pack -c Release /p:Version=${{ github.event.release.tag_name }}  /p:PackageReleaseNotes="See https://github.com/jabbekhaneh//SHJ.PersianCulture/releases/tag/${{ github.event.release.tag_name }}"
      working-directory: ./src/SHJ.PersianCulture

    - name: 📦 Archive NuGet Package
      uses: actions/upload-artifact@v1
      with:
        name: SHJ.PersianCulture
        path: ./src/SHJ.PersianCulture/bin/Release/SHJ.PersianCulture.${{ github.event.release.tag_name }}.nupkg

    - name: 🌐 Publish Nuget Package
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_AUTH_KEY }} --source https://api.nuget.org/v3/index.json --no-symbols true



    # - name: '🌐 Push package'
    #   run: dotnet nuget push src/SHJ.PersianCulture/bin/Release/*.nupkg -k ${{secrets.NUGET_AUTH_KEY}}  -s ${{ env.NUGET_SOURCE_URL }}

      
